Fix blocklet title overflow
ArcBlock/blocklets pull request #82
Opened 2020-11-17 23:54 UTC by leermao

https://github.com/ArcBlock/abt-node/issues/1759

- 修复 blocklet title 文本过长本截断问题

2020-11-17 23:55 UTC, leermao commented
![image](https://user-images.githubusercontent.com/11629887/99464589-75d80000-2973-11eb-8dd0-74ccf3a6f757.png)

2020-11-19 01:41 UTC, wangshijun requested changes

2020-11-19 01:41 UTC, wangshijun commented on src/components/blocklets.js
> +    white-space: nowrap;
这个地方直接让他折行会不会有其他问题？

另外，这个地方展示的是 name，顺便改成 title || name 吧

2020-11-19 01:44 UTC, leermao commented on src/components/blocklets.js
> +    white-space: nowrap;
> 这个地方直接让他折行会不会有其他问题？
> 
目前是长度过长时 展示省略号 前面有 overflow: hidden

2020-11-19 04:27 UTC, wangshijun approved these changes

2020-11-19 04:28 UTC, merged